
# Title: Hashing
# Author : Mustafa Mert Gülhan
# ID: 22201895
# Section : 1
# Homework : 3
# Description : Makefile for producing executables

make: build

build: substrings minimalset lexicographic insertionorders

substrings: substrings.cpp
	g++ -Wall -o substrings substrings.cpp

minimalset: minimalset.cpp
	g++ -Wall -o minimalset minimalset.cpp

lexicographic: lexicographic.cpp
	g++ -Wall -o lexicographic lexicographic.cpp

insertionorders: insertionorders.cpp
	g++ -Wall -o insertionorders insertionorders.cpp

clean:
	rm -f substrings minimalset lexicographic insertionorders

